@baseUrl = http://localhost:8080/comment

#----------------------------
# GET
#----------------------------

### COMMENT BY ID

# EXAMPLE: GET {{baseUrl}}/comment/123

@id0 =4

GET {{baseUrl}}/{{id0}}


#----------------------------
# POST
#----------------------------
### LIKE COMMENT
@id1=4
@bearer_token1 =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNb292aWUiLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjgzNjEyMiwiZXhwIjoxNzMzNDQwOTIyfQ.DH67__vKqJhHSWunS362U0O1qRptW4Gfjw35LCUqy0z8CtLlmIE-MaxkqXscQZQtE4ILqyEmRaiRaofmCXd4oA

POST {{baseUrl}}/{{id1}}/like
Authorization: Bearer {{bearer_token1}}

#----------------------------
# DELETE
#----------------------------

### DELETE COMMENT
@id2=4
@bearer_token2 =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNb292aWUiLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjgzNjEyMiwiZXhwIjoxNzMzNDQwOTIyfQ.DH67__vKqJhHSWunS362U0O1qRptW4Gfjw35LCUqy0z8CtLlmIE-MaxkqXscQZQtE4ILqyEmRaiRaofmCXd4oA

DELETE {{baseUrl}}/{{id2}}
Authorization: Bearer {{bearer_token2}}


### UNLIKE COMMENT
DELETE {{baseUrl}}/{{id2}}/removeLikeComment
Authorization: Bearer {{bearer_token2}}

### UNDISLIKE COMMENT
DELETE {{baseUrl}}/{{id2}}/removeUnlikeComment
Authorization: Bearer {{bearer_token2}}


