@baseUrl = http://localhost:8080/list

#----------------------------
# GET
#----------------------------

### LIST BY ID

# EXAMPLE: GET {{base_url}}/list/5
@bearer_token = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjc0MDc0NywiZXhwIjoxNzMzMzQ1NTQ3fQ.OKFjYIuVZktDJ6rw3XbgW2aqO0brzGhjpOkU2sJJfgFVvauDxz7hCFwnVnUnJCW_ZW8EWw6BBfcg-AFyiCh_7Q
@id0 = 27

GET {{baseUrl}}/{{id0}}
Authorization: Bearer {{bearer_token}}

### LIST CONTENT

# EXAMPLE: {{baseUrl}}/list/1/content?orderBy=name&sortOrder=ASC&page=1

@id1 = 37
@orderBy1 = ASC
@sortOrder1 = name
@page1 = 1

GET {{baseUrl}}/{{id1}}/content?orderBy={{orderBy1}}&sortOrder={{sortOrder1}}&page={{page1}}

### LIST CONTENT BY MEDIA ID

@id8 = 37
@mediaId8 = 90

GET {{baseUrl}}/{{id8}}/content/{{mediaId8}}

### LIST LIST (Still needs a lot of work to be done aa)

@page2 = 1

GET {{baseUrl}}?pageNumber={{page2}}

### Get REVIEW LIST
@id1review = 37
GET {{baseUrl}}/{{id1review}}/moovieListReviews


### GET RECOMENDED LIST
@id21 = 37

GET {{baseUrl}}/{{id21}}/recommendedLists

### GET RECOMENDED MEDIA TO ADD TO LIST
@id22 = 37

GET {{baseUrl}}/{{id22}}/recommendedMedia

#----------------------------
# POST
#----------------------------

### CREATE LIST

# POST http://localhost:8080/list
# Authorization: Bearer <your_token>
# Content-Type: application/json
#{
#  "name": "My Favorite Movies",
#  "description": "A collection of my favorite films."
#}

@bearer_token1 =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNb292aWUiLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjgzNjEyMiwiZXhwIjoxNzMzNDQwOTIyfQ.DH67__vKqJhHSWunS362U0O1qRptW4Gfjw35LCUqy0z8CtLlmIE-MaxkqXscQZQtE4ILqyEmRaiRaofmCXd4oA

POST {{baseUrl}}
Authorization: Bearer {{bearer_token1}}
Content-Type: application/json

{
  "name": "My Most hate2d but still Favorite Movies",
  "description": "A collection of my favorite films."
}

> response.json



### INSERT MEDIA INTO LIST

# POST http://localhost:8080/list/{{moovieListId1}}/content
# Authorization: Bearer <your_token>
# Content-Type: application/json
#{
#  "name": "My Favorite Movies",
#  "description": "A collection of my favorite films."
#}



@bearer_token3 = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMzkyNDk4NSwiZXhwIjoxNzM0NTI5Nzg1fQ.xW2IMFg-_W0a_jy5DgwNCBRtrMWcDFoVdiNNPj9oEj3c3FdP8iJGWpXtFp_M5GWvOvXqRHN2JWUVO_8UcMHTPA
@moovieListId1 = 4
POST {{baseUrl}}/{{moovieListId1}}/content
Authorization: Bearer {{bearer_token3}}
Content-Type: application/json

{
  "mediaIdList": [100]
}


### LIKE LIST

@moovieListId5 = 45

POST {{baseUrl}}/{{moovieListId5}}/liked
Authorization: Bearer {{bearer_token3}}
Content-Type: application/json

### LIKE LIST


DELETE {{baseUrl}}/{{moovieListId5}}/liked
Authorization: Bearer {{bearer_token3}}
Content-Type: application/json

### FOLLOW LIST

POST {{baseUrl}}/{{moovieListId1}}/followed
Authorization: Bearer {{bearer_token3}}
Content-Type: application/json

### UNFOLLOW LIST

DELETE {{baseUrl}}/{{moovieListId1}}/unfollowed
Authorization: Bearer {{bearer_token3}}
Content-Type: application/json

### REVIEW LIST
@bearer_token2_review =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNb292aWUiLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjgzNjEyMiwiZXhwIjoxNzMzNDQwOTIyfQ.DH67__vKqJhHSWunS362U0O1qRptW4Gfjw35LCUqy0z8CtLlmIE-MaxkqXscQZQtE4ILqyEmRaiRaofmCXd4oA
@id2_review = 40

POST {{baseUrl}}/{{id2_review}}/moovieListReview
Authorization: Bearer {{bearer_token2_review}}
Content-Type: application/json

{
  "reviewContent": "Test review"
}


#----------------------------
# PUT METHODS
#----------------------------

### MODIFY REVIEW LIST
@bearer_token3_review =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNb292aWUiLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjgzNjEyMiwiZXhwIjoxNzMzNDQwOTIyfQ.DH67__vKqJhHSWunS362U0O1qRptW4Gfjw35LCUqy0z8CtLlmIE-MaxkqXscQZQtE4ILqyEmRaiRaofmCXd4oA
@id3_review = 40

PUT {{baseUrl}}/{{id3_review}}/moovieListReview
Authorization: Bearer {{bearer_token3_review}}
Content-Type: application/json

{
  "reviewContent": "Test 2"
}


#----------------------------
# DELETE METHODS
#----------------------------

### DELETE LIST

@bearer_token2 = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjc0MDc0NywiZXhwIjoxNzMzMzQ1NTQ3fQ.OKFjYIuVZktDJ6rw3XbgW2aqO0brzGhjpOkU2sJJfgFVvauDxz7hCFwnVnUnJCW_ZW8EWw6BBfcg-AFyiCh_7Q

@id2 = 48

DELETE {{baseUrl}}/{{id2}}
Authorization: Bearer {{bearer_token2}}




### DELETE MEDIA FROM LIST

@bearer_token4 = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjc0MDc0NywiZXhwIjoxNzMzMzQ1NTQ3fQ.OKFjYIuVZktDJ6rw3XbgW2aqO0brzGhjpOkU2sJJfgFVvauDxz7hCFwnVnUnJCW_ZW8EWw6BBfcg-AFyiCh_7Q

@id4 = 45

DELETE {{baseUrl}}/{{id4}}/content
Authorization: Bearer {{bearer_token4}}
Content-Type: application/json

{
  "mediaIdList": [6]
}




