@baseUrl = http://localhost:8080/medias

#----------------------------
# GET
#----------------------------

### MEDIA BY ID

# EXAMPLE: GET {{baseUrl}}/media


GET {{baseUrl}}?ids=2,59,8,9,5
Content-Type: application/json

### MEDIA LIST

# EXAMPLE: {{baseUrl}}/media?type&orderBy=name&sortOrder=ASC&page=1&pageSize=5

@type1 = 1
@orderBy1 = name
@sortOrder1 = ASC
@page1 = 1
@pageSize1 = 10

GET {{baseUrl}}/search?type={{type1}}&orderBy={{orderBy1}}&sortOrder={{sortOrder1}}&page={{page1}}&pageSize={{pageSize1}}


### GET ACTORS IN MEDIA

@mediaId92 = 379

GET {{baseUrl}}/{{id}}/actors
Content-Type: */*

#----------------------------
# POST
#----------------------------

### REVIEW POST
@id=11
@bearer_token1 =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNb292aWUiLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjgzNjEyMiwiZXhwIjoxNzMzNDQwOTIyfQ.DH67__vKqJhHSWunS362U0O1qRptW4Gfjw35LCUqy0z8CtLlmIE-MaxkqXscQZQtE4ILqyEmRaiRaofmCXd4oA

POST {{baseUrl}}/{{id}}/review
Authorization: Bearer {{bearer_token1}}
Content-Type: application/json

{
  "rating": 3,
  "reviewContent":"1231232"
}

> response.json

### REVIEW EDIT
@id2=1
@bearer_token2 =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNb292aWUiLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjgzNjEyMiwiZXhwIjoxNzMzNDQwOTIyfQ.DH67__vKqJhHSWunS362U0O1qRptW4Gfjw35LCUqy0z8CtLlmIE-MaxkqXscQZQtE4ILqyEmRaiRaofmCXd4oA

PUT {{baseUrl}}/{{id2}}/review
Authorization: Bearer {{bearer_token2}}
Content-Type: application/json

{
  "rating": 2
}

> response.json
