@baseUrl = http://localhost:8080/review

#----------------------------
# GET
#----------------------------

### REVIEW BY ID

# EXAMPLE: GET {{baseUrl}}/review/123

@id0 =9

GET {{baseUrl}}/{{id0}}

### GET COMMENTS
@id0_comment =9
GET {{baseUrl}}/{{id0_comment}}/comments

#----------------------------
# POST
#----------------------------
### LIKE REVIEW
@id1=9
@bearer_token1 =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNb292aWUiLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjgzNjEyMiwiZXhwIjoxNzMzNDQwOTIyfQ.DH67__vKqJhHSWunS362U0O1qRptW4Gfjw35LCUqy0z8CtLlmIE-MaxkqXscQZQtE4ILqyEmRaiRaofmCXd4oA

POST {{baseUrl}}/{{id1}}/like
Authorization: Bearer {{bearer_token1}}

### COMMENT REVIEW
@id1_comment=9
@bearer_token_comment1 =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNb292aWUiLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjgzNjEyMiwiZXhwIjoxNzMzNDQwOTIyfQ.DH67__vKqJhHSWunS362U0O1qRptW4Gfjw35LCUqy0z8CtLlmIE-MaxkqXscQZQtE4ILqyEmRaiRaofmCXd4oA

POST {{baseUrl}}/{{id1_comment}}/comment
Authorization: Bearer {{bearer_token_comment1}}
Content-Type: application/json

{
  "commentContent": "Hello world"
}

#----------------------------
# DELETE
#----------------------------

### DELETE REVIEW
@id2=8
@bearer_token2 =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNb292aWUiLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjgzNjEyMiwiZXhwIjoxNzMzNDQwOTIyfQ.DH67__vKqJhHSWunS362U0O1qRptW4Gfjw35LCUqy0z8CtLlmIE-MaxkqXscQZQtE4ILqyEmRaiRaofmCXd4oA

DELETE {{baseUrl}}/{{id2}}
Authorization: Bearer {{bearer_token2}}



