@baseUrl = http://localhost:8080/users

#----------------------------
# GET
#----------------------------

### PROFILE

@username1 = Wancho
@bearer_token2 =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNb292aWUiLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjgzNjEyMiwiZXhwIjoxNzMzNDQwOTIyfQ.DH67__vKqJhHSWunS362U0O1qRptW4Gfjw35LCUqy0z8CtLlmIE-MaxkqXscQZQtE4ILqyEmRaiRaofmCXd4oA

GET {{baseUrl}}/profile/{{username1}}
Authorization: Bearer {{bearer_token2}}

### LOGIN

# EXAMPLE
# curl -X GET
#     -H "Authorization: Basic $(echo -n 'username:password' | base64)"
#     http://localhost:8080/users/username/username

@username2 = Moovie
@password2 = admin123

@auth2 = V2FuY2hvOnBhc3MxMg==

GET {{baseUrl}}/username/{{username2}}
Authorization: Basic {{auth2}}


### WATCHED / WATCHLIST

@username3 = Wancho
@bearer_token = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczNTMyMTMzMywiZXhwIjoxNzM1OTI2MTMzfQ.1A86G2nyz8-nHbd6ohIxv6_Ykp7A35CFAXJ0aYscaj7ekm4glmFcLw3-tTVHROPI4T7R5aQvViaTaAh7UgPXlw
@type = watchlist

GET {{baseUrl}}/{{username3}}/{{type}}
Authorization: Bearer {{bearer_token}}

### GET moovieListReviews
@id1=21
@bearer_token1 =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNb292aWUiLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjgzNjEyMiwiZXhwIjoxNzMzNDQwOTIyfQ.DH67__vKqJhHSWunS362U0O1qRptW4Gfjw35LCUqy0z8CtLlmIE-MaxkqXscQZQtE4ILqyEmRaiRaofmCXd4oA

GET {{baseUrl}}/{{id1}}/moovieListReviews

### SEARCH USERS

@searchParam = Wancho

GET {{baseUrl}}/search?username={{searchParam}}


### POST A WATCHED

@username5 = Wancho
@bearer_token26 = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczNTMyMTMzMywiZXhwIjoxNzM1OTI2MTMzfQ.1A86G2nyz8-nHbd6ohIxv6_Ykp7A35CFAXJ0aYscaj7ekm4glmFcLw3-tTVHROPI4T7R5aQvViaTaAh7UgPXlw


GET {{baseUrl}}/{{username5}}/watched
Authorization: Bearer {{bearer_token26}}
Content-Type: */*



### GET likedists

@username4=Wancho
@bearer_token23 = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczNTMyMTMzMywiZXhwIjoxNzM1OTI2MTMzfQ.1A86G2nyz8-nHbd6ohIxv6_Ykp7A35CFAXJ0aYscaj7ekm4glmFcLw3-tTVHROPI4T7R5aQvViaTaAh7UgPXlw

GET {{baseUrl}}/{{username4}}/listLikes/40
Authorization: Bearer {{bearer_token23}}
Content-Type: */*

### GET followedLists

GET {{baseUrl}}/{{username4}}/listFollows
Authorization: Bearer {{bearer_token23}}
Content-Type: */*

